# -*- coding: utf-8 -*-
"""把 renderPlate 替换为 SAO Utils 2 细长平行四边形血条(一次性补丁)。"""
import io
import sys

P = "common/src/main/java/com/sao/saomenu/client/SAOHud.java"
s = io.open(P, encoding="utf-8").read()

# 1) 尺寸委托改为宽度制
s = s.replace("""    public static int plateW(int screenH) {
        return MenuLayout.plateW(screenH);
    }

    public static int plateH(int screenH) {
        return MenuLayout.plateH(screenH);
    }""",
"""    public static int plateW(int screenW) {
        return MenuLayout.plateW(screenW);
    }

    public static int plateH(int screenW) {
        return MenuLayout.plateH(screenW);
    }""")
s = s.replace("renderPlate(g, 8, 8, plateW(h), plateH(h),",
              "renderPlate(g, 8, 8, plateW(w), plateH(w),")
s = s.replace("renderEffects(g, 8, 8 + plateH(h) + 2, p, 1f);",
              "renderEffects(g, 8, 8 + plateH(w) + 2, p, 1f);")
s = s.replace("p, 8, 8 + plateH(h) + 2, mx, my);",
              "p, 8, 8 + plateH(w) + 2, mx, my);")

# 2) 整体替换 renderPlate(从方法 javadoc 到 lerpColor 之前)
start = s.index("    /**\n     * SAO 血条板")
end = s.index("    /** 两个 ARGB 颜色按 t 线性插值")

J = []
J.append("    /**")
J.append("     * SAO 血条板(SAO Utils 2 形式,参照官方网页主题 CSS):")
J.append("     * 左侧皮肤头像徽章 + 名字底板 + 细长平行四边形血条(skewX(-30°) 斜切,")
J.append("     * 右端带台阶缺口)+ 右下深色子板(\"血量 | 上限 Lv\")。")
J.append("     * 血条为固定彩虹渐变(红→橙→黄→绿),填充宽度 = 血量比例:")
J.append("     * 满血时右端可见绿色,血量下降绿色段消失、整体趋于红色。")
J.append("     */")
J.append("    public static void renderPlate(GuiGraphics g, int x, int y, int w, int h,")
J.append("                                   String name, Player p, float alpha) {")
J.append("        float hp = p != null ? p.getHealth() : 20f;")
J.append("        float maxHp = p != null ? p.getMaxHealth() : 20f;")
J.append("        int level = p != null ? p.experienceLevel : 1;")
J.append("        // 默认字体已由模组注入 SAOUI(assets/minecraft/font/default.json),此处即 SAO 字体")
J.append("        Font font = Minecraft.getInstance().font;")
J.append("")
J.append("        // ---- 几何(参照参考图比例:细长条 + 右下子板)----")
J.append("        int barTop = y + Math.max(1, Math.round(h * 0.12f));")
J.append("        int barH = Math.max(4, Math.round(h * 0.36f));")
J.append("        int barBot = barTop + barH;")
J.append("        int skewH = Math.max(2, Math.round(barH * 0.6f));  // skewX(-30°) 的水平偏移")
J.append("        int badgeW = barH + 4;")
J.append("        int badgeX = x + 1;")
J.append("        int badgeY = barTop - 2;")
J.append("        int badgeH = barH + 4;")
J.append("        int slabStart = badgeX + badgeW;")
J.append("        int barLeft = Math.max(x + Math.round(w * 0.30f), slabStart + font.width(name) + 12);")
J.append("        int barEnd = x + Math.round(w * 0.955f);")
J.append("        int capW = Math.max(4, Math.round((barEnd - barLeft) * 0.06f)); // 右端台阶缺口宽")
J.append("        int subTop = barBot + 1;")
J.append("        int subH = Math.max(8, y + h - subTop - 1);")
J.append("        int subX = x + Math.round(w * 0.52f);")
J.append("")
J.append("        // ---- 名字底板(徽章右侧,略高于血条;血条左斜切露在其上)----")
J.append("        g.fill(badgeX, badgeY, barLeft + skewH, barBot + 2, mulAlpha(SLAB_DARK, alpha));")
J.append("        g.fill(badgeX, badgeY, barLeft + skewH, badgeY + 1, mulAlpha(SLAB_EDGE, alpha));")
J.append("")
J.append("        // ---- 血条:外框(半透明白描边)→ 深色轨道 → 彩虹填充 ----")
J.append("        float frac = maxHp <= 0 ? 0f : Mth.clamp(hp / maxHp, 0f, 1f);")
J.append("        drawSkewedBar(g, barLeft, barTop, barEnd, barBot, skewH, capW, frac, alpha);")
J.append("")
J.append("        // ---- 头像徽章(皮肤脸 + 描边;保留头像)----")
J.append("        g.fill(badgeX, badgeY, badgeX + badgeW, badgeY + badgeH, mulAlpha(SLAB_DARK, alpha));")
J.append("        g.fill(badgeX, badgeY, badgeX + badgeW, badgeY + 1, mulAlpha(SLAB_EDGE, alpha));")
J.append("        if (SAOConfig.showAvatar() && p != null) {")
J.append("            int pad = Math.max(1, Math.round(badgeW * 0.1f));")
J.append("            renderAvatar(g, Minecraft.getInstance(), p,")
J.append("                    badgeX + pad, badgeY + pad, badgeW - pad * 2, alpha);")
J.append("        } else {")
J.append('            String plus = "+";')
J.append("            g.drawString(font, plus, badgeX + (badgeW - font.width(plus)) / 2,")
J.append("                    badgeY + (badgeH - 8) / 2, mulAlpha(TEXT_WHITE, alpha), false);")
J.append("        }")
J.append("")
J.append("        // ---- 名字(名字底板上,垂直居中)----")
J.append("        int nameY = badgeY + (badgeH - 8) / 2;")
J.append("        g.drawString(font, name, badgeX + badgeW + 4, nameY, mulAlpha(TEXT_WHITE, alpha), false);")
J.append("")
J.append('        // ---- 右下子板:血量 | 上限 Lv ----')
J.append("        g.fill(subX, subTop, x + w - 1, subTop + subH, mulAlpha(SUB_DARK, alpha));")
J.append("        g.fill(subX, subTop, x + w - 1, subTop + 1, mulAlpha(SLAB_EDGE, alpha));")
J.append('        String text = tr("saomenu.plate.hp", trimHp(hp), trimHp(maxHp), level);')
J.append("        g.drawString(font, text, x + w - 4 - font.width(text),")
J.append("                subTop + (subH - 8) / 2, mulAlpha(TEXT_WHITE, alpha), false);")
J.append("")
J.append("        // ---- 受击闪红:整个板叠一层快速衰减的红色 ----")
J.append("        long flashAge = net.minecraft.Util.getMillis() - flashAt;")
J.append("        if (flashAge >= 0 && flashAge < FLASH_MS) {")
J.append("            float fa = (1f - flashAge / (float) FLASH_MS) * alpha;")
J.append("            g.fill(x, badgeY, x + w, subTop + subH, mulAlpha(0x59FF3030, fa));")
J.append("        }")
J.append("")
J.append("        // ---- 低血量脉冲:轨道内叠加呼吸式红光 ----")
J.append("        if (frac > 0f && frac < 0.2f) {")
J.append("            float pulse = 0.35f + 0.45f * Mth.sin(net.minecraft.Util.getMillis() / 130f);")
J.append("            overlaySkewedBar(g, barLeft, barTop, barEnd, barBot, skewH, capW,")
J.append("                    mulAlpha(0x66FF2020, pulse * alpha));")
J.append("        }")
J.append("    }")
J.append("")
J.append("    /** 平行四边形血条:外框 + 深色轨道 + 彩虹渐变填充(宽度=血量)+ 右端台阶缺口。 */")
J.append("    private static void drawSkewedBar(GuiGraphics g, int left, int top, int right, int bot,")
J.append("                                      int skewH, int capW, float frac, float alpha) {")
J.append("        // 外描边(半透明白,CSS: border 1px solid rgba(255,255,255,0.5))")
J.append("        overlaySkewedBar(g, left - 1, top - 1, right + 1, bot + 1, skewH, capW,")
J.append("                mulAlpha(0x80F0F0F0, alpha));")
J.append("        // 深色轨道")
J.append("        for (int cx = left; cx < right + skewH; cx++) {")
J.append("            int yTop = skewTop(top, bot, skewH, left, cx);")
J.append("            int yBot = skewBottom(top, bot, skewH, right, cx);")
J.append("            if (yBot <= yTop) {")
J.append("                continue;")
J.append("            }")
J.append("            g.fill(cx, yTop, cx + 1, yBot, mulAlpha(TRACK_BASE, alpha));")
J.append("        }")
J.append("        // 彩虹填充(固定渐变红→橙→黄→绿,宽度=血量;CSS .HP-health)")
J.append("        int innerW = (right - capW - 2) - (left + 1);")
J.append("        int fillW = Math.round(innerW * frac);")
J.append("        for (int cx = left + 1; cx < left + 1 + fillW && cx < right + skewH; cx++) {")
J.append("            int yTop = skewTop(top, bot, skewH, left, cx);")
J.append("            int yBot = skewBottom(top, bot, skewH, right, cx);")
J.append("            if (yBot <= yTop) {")
J.append("                continue;")
J.append("            }")
J.append("            float t = Mth.clamp((cx - left - 1) / (float) Math.max(1, innerW), 0f, 1f);")
J.append("            int color = 0xFF000000 | rainbow(t);")
J.append("            // 右端台阶缺口段:高度压到下部并压暗(参考图右端小台阶)")
J.append("            if (cx >= right - capW) {")
J.append("                int cut = Math.max(1, (yBot - yTop) * 45 / 100);")
J.append("                yTop += cut;")
J.append("                color = mulAlpha(color, 0.72f);")
J.append("            }")
J.append("            g.fill(cx, yTop, cx + 1, yBot, mulAlpha(color, alpha));")
J.append("        }")
J.append("    }")
J.append("")
J.append("    /** 在平行四边形区域内叠加一层纯色(低血脉冲复用)。 */")
J.append("    private static void overlaySkewedBar(GuiGraphics g, int left, int top, int right, int bot,")
J.append("                                         int skewH, int capW, int color) {")
J.append("        for (int cx = Math.max(0, left); cx < right + skewH; cx++) {")
J.append("            int yTop = skewTop(top, bot, skewH, left, cx);")
J.append("            int yBot = skewBottom(top, bot, skewH, right, cx);")
J.append("            if (cx >= right - capW) {")
J.append("                int cut = Math.max(1, (yBot - yTop) * 45 / 100);")
J.append("                yTop += cut;")
J.append("            }")
J.append("            if (yBot > yTop) {")
J.append("                g.fill(cx, yTop, cx + 1, yBot, color);")
J.append("            }")
J.append("        }")
J.append("    }")
J.append("")
J.append("    /** 平行四边形上边缘:顶行右移 skewH(左端斜切)。 */")
J.append("    private static int skewTop(int top, int bot, int skewH, int left, int cx) {")
J.append("        int over = skewH - (cx - left);")
J.append("        return over > 0 ? top + over * (bot - top) / skewH : top;")
J.append("    }")
J.append("")
J.append("    /** 平行四边形下边缘:底行右端最早结束(右端斜切)。 */")
J.append("    private static int skewBottom(int top, int bot, int skewH, int right, int cx) {")
J.append("        int over = (cx + 1) - right;")
J.append("        return over > 0 ? bot - over * (bot - top) / skewH : bot;")
J.append("    }")
J.append("")
J.append("    /** 官方 .HP-health 渐变:红(0)→橙(1/3)→黄(2/3)→绿(1)。t∈[0,1]。 */")
J.append("    private static int rainbow(float t) {")
J.append("        t = Mth.clamp(t, 0f, 1f);")
J.append("        float[][] stops = {")
J.append("                {255f, 0f, 0f}, {255f, 168f, 0f}, {255f, 242f, 0f}, {30f, 150f, 0f}")
J.append("        };")
J.append("        float p = t * (stops.length - 1);")
J.append("        int i = Math.min((int) p, stops.length - 2);")
J.append("        float u = p - i;")
J.append("        int r = Math.round(stops[i][0] + (stops[i + 1][0] - stops[i][0]) * u);")
J.append("        int gg = Math.round(stops[i][1] + (stops[i + 1][1] - stops[i][1]) * u);")
J.append("        int bb = Math.round(stops[i][2] + (stops[i + 1][2] - stops[i][2]) * u);")
J.append("        return (r << 16) | (gg << 8) | bb;")
J.append("    }")
J.append("")

new_method = "\n".join(J) + "\n"
s = s[:start] + new_method + s[end:]
io.open(P, "w", encoding="utf-8").write(s)
print("renderPlate rewritten ok")
